# Generated by Django 5.0.2 on 2024-02-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restr', '0002_alter_menuitem_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('menu_photo', models.ImageField(blank=True, upload_to='photos')),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='restr.menu'),
        ),
    ]
