# Generated by Django 5.0.2 on 2024-02-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restr', '0003_menu_alter_restaurant_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('restaurant', models.CharField(max_length=100)),
                ('desired_table', models.CharField(max_length=100)),
            ],
        ),
    ]
