# Generated by Django 5.0.2 on 2024-02-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restr', '0005_alter_reservation_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(max_length=100),
        ),
    ]
